name: Run tests on push to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run Pytest
      run: |
        cd dslsplit
        pytest tests/

    - name: Check for failures
      run: |
        if [ $? -ne 0 ]; then
          echo "Pytest failed. Please fix the errors and try again."
          exit 1
        fi
